name: Neoxr Bot Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        env:
          DATABASE_URL: ${{ secrets.MONGO_URL }}
          OWNER: ${{ secrets.OWNER }}
          PAIRING_NUMBER: ${{ secrets.PAIRING_NUMBER }}
        run: npm start
